// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::drivetrainaMotor = NULL;
SpeedController* RobotMap::drivetrainbMotor = NULL;
SpeedController* RobotMap::drivetraincMotor = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	drivetrainaMotor = new TalonSRX(3);
	lw->AddActuator("Drivetrain", "aMotor", (TalonSRX*) drivetrainaMotor);
	
	drivetrainbMotor = new TalonSRX(4);
	lw->AddActuator("Drivetrain", "bMotor", (TalonSRX*) drivetrainbMotor);
	
	drivetraincMotor = new TalonSRX(5);
	lw->AddActuator("Drivetrain", "cMotor", (TalonSRX*) drivetraincMotor);
	

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
